# Generated by Django 4.2.6 on 2023-10-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('ddd', models.CharField(max_length=2)),
                ('numero_telefone', models.CharField(max_length=9, unique=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('cpf_cnpj', models.CharField(max_length=15, unique=True)),
            ],
        ),
    ]
